### ISSUE TITLE
download button not work

### ISSUE THREAD

**Issue by souarit** [mybbgroup/MyBB_Fancybox#14]
thank you very much for this awesome plugin.
after test i see that download button not start downloading the image , only the image link is shown in address panel of browser.

thank you.

**Comment by Eldenroot** [comment]
It happens only when the image is added into the post, right? It should work as expected when you click on image inside the attachment box. Unfortunately this cannot be fixed, you can download image by mouse right click.

**Comment by souarit** [comment]
that's right..thank you .
other thing...(;. is there any idea to deactivate the plugin for some image?

**Comment by Eldenroot** [comment]
For which images? In posts?

**Comment by souarit** [comment]
yes in the post i want that some images not be shown in tha fanybox.

**Comment by Eldenroot** [comment]
Not possible, you will have to modify js file
