### ISSUE TITLE
Previous&Next / Slideshow

### ISSUE THREAD

**Issue by souarit** [mybbgroup/MyBB_Fancybox#18]
hello;
i m asking if there is a possibility to add or activate slideshow option and navigation option (previous/next) because its very useful when wa have many pictures in a post..

thanks.

**Comment by Eldenroot** [comment]
It should be working - I added support for that in my last release - please try to update and let me know.

**Comment by souarit** [comment]
ohhh ..thank you  its working perfectlly !!

other thing please .. its possible to shoose and fix zoom when navigate or in in slideshow?

**Comment by Eldenroot** [comment]
I dont understand to your question, how to reproduce, describe better and add images... Thank you

**Comment by souarit** [comment]
when i shoose a zoom 80% for example...when i click on next the zoom is reset to default ...so i want that the zoom willl be fixed clicking next/previous.

**Comment by Eldenroot** [comment]
Thats not possible, every image has different dimensions.
