### ISSUE TITLE
Add basic lang support

### ISSUE THREAD

**Issue by Eldenroot** [mybbgroup/MyBB_Fancybox#9]

**Comment by Eldenroot** [comment]
@WildcardSearch - can you please help me to get this working? First of all I need to add a basic support for langs in templates... JS (mybbfancybox.js) will be translated later, this is something quite difficult to add support for translating external JS file.

No rush ;) thank you buddy!

**Comment by WildcardSearch** [comment]
Of course, @Eldenroot. I will try my best to get a PR submitted this weekend.

**Comment by Eldenroot** [comment]
First part was added via https://github.com/mybbgroup/MyBB_Fancybox/pull/20, JS part will be added later. Thank you @WildcardSearch
